// <auto-generated />
using System;
using BooksTracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BooksTracker.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20200923015340_UpdateDate")]
    partial class UpdateDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BooksTracker.Models.Author", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("author");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Name = "Nora Roberts"
                        },
                        new
                        {
                            ID = -2,
                            Name = "Stephen King"
                        },
                        new
                        {
                            ID = -3,
                            Name = "Jane Austen"
                        },
                        new
                        {
                            ID = -4,
                            Name = "Zadie Smith"
                        },
                        new
                        {
                            ID = -5,
                            Name = "George Orewell"
                        },
                        new
                        {
                            ID = -6,
                            Name = "Jess Kidd"
                        });
                });

            modelBuilder.Entity("BooksTracker.Models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(10)");

                    b.Property<int>("AuthorID")
                        .HasColumnName("AuthorID")
                        .HasColumnType("int(10)");

                    b.Property<DateTime>("CheckedOutDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.HasIndex("AuthorID")
                        .HasName("FK_Book_Author");

                    b.ToTable("book");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            AuthorID = -1,
                            CheckedOutDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(1, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublicationDate = new DateTime(2013, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Key of Light"
                        },
                        new
                        {
                            ID = -2,
                            AuthorID = -2,
                            CheckedOutDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(1, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublicationDate = new DateTime(2001, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Once Upon a Rose"
                        },
                        new
                        {
                            ID = -3,
                            AuthorID = -3,
                            CheckedOutDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(1, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublicationDate = new DateTime(2005, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Blue Smoke"
                        },
                        new
                        {
                            ID = -4,
                            AuthorID = -4,
                            CheckedOutDate = new DateTime(2020, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(1, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublicationDate = new DateTime(1977, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shining"
                        },
                        new
                        {
                            ID = -5,
                            AuthorID = -5,
                            CheckedOutDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(1, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublicationDate = new DateTime(2013, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Doctor Sleep"
                        });
                });

            modelBuilder.Entity("BooksTracker.Models.Book", b =>
                {
                    b.HasOne("BooksTracker.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorID")
                        .HasConstraintName("FK_Book_Author")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
